Завдання 1. Підрахунок загальної кількості респондентів

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r'C:/Users/Admin/Desktop/моя/project Pyton/data_stack_overflow/survey_results_public.csv', encoding = 'utf-8')

C:\Users\Admin\AppData\Local\Temp\ipykernel_5560\1215110640.py:1: DtypeWarning: Columns (56,74,92,97,98,105,109,110,132,162,165) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r'C:/Users/Admin/Desktop/моя/project Pyton/data_stack_overflow/survey_results_public.csv', encoding = 'utf-8')

In [4]:
df1 = pd.read_csv(r'C:/Users/Admin/Desktop/моя/project Pyton/data_stack_overflow/survey_results_schema.csv', encoding = 'utf-8')

In [5]:
pd.set_option('display.max_columns', None)

In [6]:
df.head(2)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0

In [7]:
number_uniq = 	df['ResponseId'].nunique()

In [8]:
print("Загальна кількость респондентів:", number_uniq)

Загальна кількость респондентів: 49191

Завдання 2. Аналіз повноти відповідей респондентів

In [9]:
#список питань з файлу survey_results_schema (поле "qname")
questions = df1['qname']
questions

0        TechEndorse_1
1        TechEndorse_2
2        TechEndorse_3
3        TechEndorse_4
4        TechEndorse_5
            ...
134    AIAgentObsWrite
135    AIAgentExternal
136    AIAgentExtWrite
137            AIHuman
138             AIOpen
Name: qname, Length: 139, dtype: object

In [10]:
#використано інтерсекцію множин
result = set(df.columns).intersection(set(questions.unique()))
result

{'AIAcc',
 'AIAgentChange',
 'AIAgentExtWrite',
 'AIAgentExternal',
 'AIAgentKnowWrite',
 'AIAgentKnowledge',
 'AIAgentObsWrite',
 'AIAgentObserveSecure',
 'AIAgentOrchWrite',
 'AIAgentOrchestration',
 'AIAgent_Uses',
 'AIAgents',
 'AIComplex',
 'AIExplain',
 'AIFrustration',
 'AIHuman',
 'AILearnHow',
 'AIModelsChoice',
 'AIModelsHaveEntry',
 'AIModelsWantEntry',
 'AIOpen',
 'AISelect',
 'AISent',
 'AIThreat',
 'Age',
 'AgentUsesGeneral',
 'CommPlatformHaveEntr',
 'CommPlatformWantEntr',
 'CompTotal',
 'Country',
 'Currency',
 'DatabaseChoice',
 'DatabaseHaveEntry',
 'DatabaseWantEntry',
 'DevEnvHaveEntry',
 'DevEnvWantEntry',
 'DevEnvsChoice',
 'DevType',
 'EdLevel',
 'Employment',
 'EmploymentAddl',
 'ICorPM',
 'Industry',
 'JobSat',
 'JobSatPoints_1',
 'JobSatPoints_10',
 'JobSatPoints_11',
 'JobSatPoints_13',
 'JobSatPoints_14',
 'JobSatPoints_15',
 'JobSatPoints_15_TEXT',
 'JobSatPoints_16',
 'JobSatPoints_2',
 'JobSatPoints_3',
 'JobSatPoints_4',
 'JobSatPoints_5',
 'JobSatPoints_6',
 'JobSatPoints_7',
 'JobSatPoints_8',
 'JobSatPoints_9',
 'LanguageChoice',
 'LanguagesHaveEntry',
 'LanguagesWantEntry',
 'LearnCode',
 'LearnCodeAI',
 'LearnCodeChoose',
 'MainBranch',
 'NewRole',
 'OfficeStackHaveEntry',
 'OfficeStackWantEntry',
 'OrgSize',
 'PlatformChoice',
 'PlatformHaveEntry',
 'PlatformWantEntry',
 'PurchaseInfluence',
 'RemoteWork',
 'SOAccount',
 'SOComm',
 'SODuration',
 'SOFriction',
 'SOPartFreq',
 'SOTagsHaveEntry',
 'SOTagsWant Entry',
 'SOVisitFreq',
 'SO_Actions_1',
 'SO_Actions_10',
 'SO_Actions_15',
 'SO_Actions_15_TEXT',
 'SO_Actions_16',
 'SO_Actions_3',
 'SO_Actions_4',
 'SO_Actions_5',
 'SO_Actions_6',
 'SO_Actions_7',
 'SO_Actions_9',
 'SO_Dev_Content',
 'TechEndorseIntro',
 'TechEndorse_1',
 'TechEndorse_13',
 'TechEndorse_13_TEXT',
 'TechEndorse_2',
 'TechEndorse_3',
 'TechEndorse_4',
 'TechEndorse_5',
 'TechEndorse_6',
 'TechEndorse_7',
 'TechEndorse_8',
 'TechEndorse_9',
 'TechOppose_1',
 'TechOppose_11',
 'TechOppose_13',
 'TechOppose_15',
 'TechOppose_15_TEXT',
 'TechOppose_16',
 'TechOppose_2',
 'TechOppose_3',
 'TechOppose_5',
 'TechOppose_7',
 'TechOppose_9',
 'ToolCountPersonal',
 'ToolCountWork',
 'WebframeChoice',
 'WebframeHaveEntry',
 'WebframeWantEntry',
 'WorkExp',
 'YearsCode'}

In [11]:
cols = df.columns[df.columns.isin(result)]
cols

Index(['MainBranch', 'Age', 'EdLevel', 'Employment', 'EmploymentAddl',
       'WorkExp', 'LearnCodeChoose', 'LearnCode', 'LearnCodeAI', 'AILearnHow',
       ...
       'AIAgentKnowWrite', 'AIAgentOrchestration', 'AIAgentOrchWrite',
       'AIAgentObserveSecure', 'AIAgentObsWrite', 'AIAgentExternal',
       'AIAgentExtWrite', 'AIHuman', 'AIOpen', 'JobSat'],
      dtype='object', length=126)

In [12]:
#Перевірити наявність відповідей на ці питання у кожного респондента
clean_data = df.dropna(subset = cols)

In [13]:
print("Кількість респондентів, що відповіли на всі питання у обраних колонках:", clean_data.shape[0])

Кількість респондентів, що відповіли на всі питання у обраних колонках: 0

Завдання 3. Статистичний аналіз досвіду респондентів

In [14]:
#Середнє значення (mean) для поля WorkExp
avg = round(df['WorkExp'].mean(), 1)
#Медіана (median)
med = round(df['WorkExp'].median(), 1)
#Моду (mode)
mod = round(df["WorkExp"].mode(), 1)
print(f'Міра центральної тенденції:')
print(f'Середнє значення: {avg}') 
print(f'Медіана: {med}') 
print(f'Мода: {mod}')

Міра центральної тенденції:
Середнє значення: 13.4
Медіана: 10.0
Мода: 0    10.0
Name: WorkExp, dtype: float64

Завдання 4. Аналіз віддаленої роботи

In [15]:
#кількість респондентів, які працюють віддалено (remote).
remote_respondents = df.loc[df['RemoteWork'] == 'Remote']
print(f'Кількість респондентів, які працюють віддалено: {remote_respondents.shape[0]}')

Кількість респондентів, які працюють віддалено: 10931

Завдання 5. Визначення популярності Python

In [16]:
#створюємо стовпець worked_with_python , який приймає значення true/false
#true означає, що респондент зазначив python у

In [18]:
df['worked_with_python'] = df['LanguageHaveWorkedWith'].str.contains('python', case=False, na = False)

In [19]:
#рахуємо кількість респондентів, які працювали в python
countx = df['worked_with_python'].sum()

In [20]:
county = df['LanguageHaveWorkedWith'].count()

In [21]:
#рахуємо значення у відсотках
rate = round((countx/county*100), 1)

In [22]:
print(f'Відсоток респондентів: {rate} %')

Відсоток респондентів: 58.3 %

Завдання 6. Аналіз шляхів навчання програмуванню

In [23]:
#кількість респондентів навчалося програмувати за допомогою онлайн курсів.

In [26]:
df['Learned_with_online_courses'] = df['LearnCode'].str.contains('online courses', case=False, na = False)

In [27]:
count_online_students = df['Learned_with_online_courses'].sum()

In [28]:
print(f'Кількість респондентів, що закінчити онлайн курси: {count_online_students}')

Кількість респондентів, що закінчити онлайн курси: 10973

Завдання 7. Географічний аналіз компенсації Python-розробників

In [29]:
# обираємо респондентів, які працюють в Pythone
new_df = df[df['worked_with_python'].isin([True])]

In [31]:
# видаляємо строки з відсутніми записами в колонці компенсації - 'ConvertedCompYearly'
new2_df = new_df.dropna(subset=['ConvertedCompYearly'])

In [33]:
#групуємо респондентів по країнам
grouped = new2_df.groupby('Country')

In [34]:
#рахуємо середнє начення середнє значення компенсації та медіану
py_proges_by_country = round(grouped['ConvertedCompYearly'].agg(['mean', 'median']),2)

In [119]:
py_proges_by_country.reset_index()

                                  Country       mean    median
0                             Afghanistan   22328.67    1000.0
1                                 Albania   47217.60   50000.0
2                                 Algeria   20187.29    7088.0
3                                 Andorra  226103.50  226103.5
4                     Antigua and Barbuda       1.00       1.0
..                                    ...        ...       ...
148  Venezuela, Bolivarian Republic of...    9908.65    3000.0
149                              Viet Nam  218837.17    8254.0
150                                 Yemen   32929.50   23672.0
151                                Zambia    5424.25    3206.0
152                              Zimbabwe   34000.00   25500.0

[153 rows x 3 columns]

Завдання 8. Аналіз освіти найбільш оплачуваних спеціалістів

In [37]:
#обираємо колнки: 'ResponseId', 'EdLevel', 'ConvertedCompYearly'
ed_convert = df[['ResponseId', 'EdLevel', 'ConvertedCompYearly']]

In [38]:
#сортуємо за колонкою 'ConvertedCompYearly' за спаданням 
ed_convert.sort_values(by=['ConvertedCompYearly'], ascending = False, inplace = True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_5560\1238771664.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ed_convert.sort_values(by=['ConvertedCompYearly'], ascending = False, inplace = True)

In [39]:
ed_convert.reset_index(drop = True, inplace = True)

*Завдання 9. Аналіз популярності Python по віковим категоріям

In [41]:
#Інструмент, який потрібен для виконання цього завдання: Pandas (групування, підрахунок відсотків, агрегація)
#Опис завдання: Для кожної вікової категорії визнач відсоток респондентів, 
#які програмують на Python. Це дасть уявлення про те, в яких вікових групах Python є найпопулярнішим.

In [53]:
#групуємо респондентів по віковим категорія і проводмио агрегацію: sum, count, де sum - кількість респондентів, що прцюютьв python
# count - загальна кількіст респондентів.
age_grouped = df.groupby('Age')['worked_with_python'].agg(['sum', 'count'])
#знаходимо відсоток тих, хто працює в python
age_grouped['rate'] = round(age_grouped['sum']/age_grouped['count']*100, 1)

In [52]:
age_grouped.reset_index()

                 Age   sum  count  rate
0    18-24 years old  3684   9210  40.0
1    25-34 years old  6102  16519  36.9
2    35-44 years old  4862  13241  36.7
3    45-54 years old  2424   6275  38.6
4    55-64 years old   978   2626  37.2
5  65 years or older   298    942  31.6
6  Prefer not to say   118    378  31.2

*Завдання 10. Аналіз індустрій серед високооплачуваних віддалених працівників

In [ ]:
#Інструмент, який потрібен для виконання цього завдання: Pandas (перцентилі, множинна фільтрація, підрахунок частоти)
#Опис завдання: Знайди респондентів, які:
#Знаходяться у 75 перцентилі за компенсацією (тобто заробляють більше, ніж 75% респондентів)
#Працюють віддалено
#Для цієї групи визнач найрозповсюдженіші індустрії.

In [ ]:
*Завдання 10. Аналіз індустрій серед високооплачуваних віддалених працівників

In [111]:
*Завдання 10. Аналіз індустрій серед високооплачуваних віддалених працівників
import numpy as np
# видаляю строки, де відсутній запис в строкі компенсації
df_sorted_conv = df.dropna(subset = ['ConvertedCompYearly'])
# сортую строки, за зростанням в стовпчику компенсації
df_sorted_conv.sort_values(by='ConvertedCompYearly',inplace =True, ascending = False )
# знаходжу 75% перцентиль
percentile_75 = np.percentile(df_sorted_conv['ConvertedCompYearly'], 75)

C:\Users\Admin\AppData\Local\Temp\ipykernel_5560\501617121.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sorted_conv.sort_values(by='ConvertedCompYearly',inplace =True, ascending = False )

In [112]:
print(percentile_75)

120596.0

In [113]:
# вибираю тих респондентів, компенсація яких вище 75% прецентеля та які працюють віддалено
df_sorted_conv = df_sorted_conv.loc[(df_sorted_conv['ConvertedCompYearly'] > percentile_75) & (df_sorted_conv['RemoteWork'] == 'Remote')]

In [114]:
df_sorted_conv['Industry'].mode()

0    Software Development
Name: Industry, dtype: object

In [115]:
# групую респондентів по галузі, і підраховую кількість по кожній залузі
df_top = df_sorted_conv.groupby('Industry')['Industry'].count()

In [116]:
#сортую значення частоти галузі по спаданню
df_top = df_top.sort_values(ascending= False)

In [125]:
print(df_top)

Industry
Software Development                          1186
Fintech                                        190
Healthcare                                     188
Other:                                         176
Internet, Telecomm or Information Services     138
Banking/Financial Services                      88
Government                                      78
Media & Advertising Services                    75
Retail and Consumer Services                    65
Transportation, or Supply Chain                 63
Computer Systems Design and Services            59
Insurance                                       46
Energy                                          45
Manufacturing                                   33
Higher Education                                30
Name: Industry, dtype: int64